### ISSUE TITLE
Lookbehind RegExp assertion not supported in Safari

### ISSUE THREAD

**Issue by zacksmash** [rudashi/stringable#29]
The `snake()` method is currently using a [lookbehind](https://github.com/rudashi/stringable/blob/78841ed2496ec1e34e48d8b1d3581d5534210cd5/src/Stringable.ts#L704) assertion in the regular expression it's running which is not completely supported in Safari.

This is causing some build errors on some of my projects, using WebPack. I've made the change using this RegExp instead:

```js
// Line 704 Stringable.ts
.replace(new RegExp(/(^|\s)\S/, 'gu'), s => s.toLocaleUpperCase())
```

Which should work the exact same, except without the lookbehind. Is this something you would consider merging if I were to create a PR for it?

**Comment by rudashi** [comment]
Sure, your solution is good
